### ISSUE TITLE
Typescript & updated package errors

### ISSUE THREAD

**Issue by ap-1** [FunMiles/SveltekitPWA#6]
`Error: $page.path has been replaced by $page.url.pathname`
src/lib/Header/index.svelte (18, 19, 20)

`Error: request.query has been replaced by request.url.searchParams`
src/hooks.ts (10, 11)

`Could not find a declaration file for module 'cookie'. ts(7016)`
src/hooks.ts (1)

`Property 'render' does not exist on type '{ request: ServerRequest<Record<string, any>, unknown>; resolve(request: ServerRequest<Record<string, any>, unknown>): MaybePromise<ServerResponse>; }'. ts(2339)`
src/hooks.ts (5, 14)

`Object is possibly 'null'. ts(2531)`
src/hooks.ts (11)

`Binding element 'url' implicitly has an 'any' type. ts(7031)`
src/service-worker.ts (43)

**Comment by FunMiles** [comment]
The first few things are fixed. I will check the complete list soon.
