### ISSUE TITLE
Auditing with Lighthouse (Chrome Dev tools), throws `Failed to register...`, but works elsewhere.

### ISSUE THREAD

**Issue by inspiredlabs** [FunMiles/SveltekitPWA#8]
Thank you for writing this straight forward ServiceWorker, I've tested many, but yours is stable and working OOTB! 🙂

Issue: End-to-end testing works on desktop and mobile, offline – but auditing with Lighthouse (Chrome Dev tools), throws:

```
cannot register service worker DOMException: Failed to register a ServiceWorker for scope ('https://offline-phi.vercel.app/') with script ('https://offline-phi.vercel.app/service-worker.js'): Operation has been aborted
```

This app can not get past ~80% and takes a long time to cancel the audit in [Chrome Dev tools, Lighthouse](https://offline-phi.vercel.app/).

Do you have any suggestions? It'd be useful to be able to speed test the template before adding content.

**Comment by FunMiles** [comment]
@inspiredlabs Thanks for the note on this example working OOTB.
I think that with the latest Sveltekit versions, I will have to do a few changes for it to work OOTB again. Most are not related to workbox but to some changes in sveltekit packaging.

On your Lighhouse note, sorry I did not reply earlier. However I think it was a problem with Lighthouse. A test today shows Lighthouse working and giving only one complaint:
```
Manifest doesn't have a maskable icon
```
